[package]
name = "rustling-ml"
version = "0.9.1"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
failure = "0.1"
fnv = "1.0"
serde = { version = "1.0", features = ["derive"] }
